// Mocks generated by Mockito 5.0.13 from annotations
// in permission_builder/test/permissive_builder_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_builder/src/permission_service.dart' as _i2;
import 'package:permission_handler/permission_handler.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [PermissionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsService extends _i1.Mock implements _i2.PermissionService {
  MockPermissionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PermissionStatus> status(_i4.Permission? permission) =>
      (super.noSuchMethod(Invocation.method(#status, [permission]),
              returnValue: Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<bool> openAppSettings() =>
      (super.noSuchMethod(Invocation.method(#openAppSettings, []),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<_i4.PermissionStatus> request(_i4.Permission? permission) =>
      (super.noSuchMethod(Invocation.method(#request, [permission]),
              returnValue: Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  String toString() => super.toString();
}
