name: permission_builder
description: A package thats a wraps around [permission_handler](https://pub.dev/packages/permission_handler) to help you handle your permissions more elegantly.
version: 0.1.0
homepage: https://github.com/bettdouglas/flutter_permission_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.0
  permission_handler: ^8.1.4+2
  provider: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito:
  freezed: ^0.14.0