name: permission_builder
description: A package thats a wraps around [permission_handler](https://pub.dev/packages/permission_handler) to help you handle your permissions more elegantly.
version: 0.0.2
homepage: https://github.com/bettdouglas/flutter_permission_builder

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  freezed: ^0.12.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.7
  mockito:


flutter:
